version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: etc/Dockerfile
    command: /bin/bash -c "adev runserver -v"
    ports:
      - "8000:8000"
    env_file:
      - ./etc/local.env
    volumes:
      - .:/code
    depends_on:
      - redis

  celery_worker:
    restart: always
    build:
      context: .
      dockerfile: etc/Dockerfile
    command: /bin/bash -c "python3 etc/wait-for.py && celery -A app.tasks worker -l info"
    env_file:
      - ./etc/local.env
    depends_on:
      - rabbitmq

  celery_beat:
    restart: always
    build:
      context: .
      dockerfile: etc/Dockerfile
    command: /bin/bash -c "python3 etc/wait-for.py && celery -A app.tasks beat -l info"
    env_file:
      - ./etc/local.env
    depends_on:
      - rabbitmq

  redis:
    restart: always
    image: redis:latest
    volumes:
      - ./docker_data/redis:/data

  rabbitmq:
    restart: always
    image: rabbitmq:3.7
    volumes:
      - ./docker_data/rabbitmq:/var/lib/rabbitmq

  redis_node1:
    restart: always
    image: redis:latest
    volumes:
      - ./docker_data/redis_node1:/data

  redis_node2:
    restart: always
    image: redis:latest
    volumes:
      - ./docker_data/redis_node2:/data
